import Head from 'next/head';
import { Button } from 'ui';

const Web = () => (
  <div>
    <Head>
      <title>Home page | Turborepo boilerplate</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
      <div className="mx-auto mt-4 max-w-screen-lg">
        <h1 className="text-6xl font-bold text-center">Turborepo | nextjs | i18n</h1>
        <div className="mt-8 text-center">
          <p>
            Boilerplate and Starter for turborepo with Next.js, Tailwind CSS and TypeScript ⚡️ Made
            with developer experience first: Next.js, TypeScript, ESLint, Prettier, Husky,
            Lint-Staged, Jest, React Testing Library, PostCSS, Tailwind CSS, Storybook, GH actions.
          </p>
        </div>
        <h2 className="text-bold mt-8 text-3xl">🚀 Features:</h2>
        <ul className="ml-6 mt-6 list-disc">
          <li>Next.js for Static Site Generator</li>
          <li>Type checking TypeScript</li>
          <li>Integrate with Tailwind CSS</li>
          <li>Storybook for components documentation</li>
          <li>Strict Mode for TypeScript and React 18</li>
          <li>Linter with ESLint</li>
          <li>Code Formatter with Prettier</li>
          <li>Husky for Git Hooks</li>
          <li>Lint-staged for running linters on Git staged files</li>
          <li>Testing with Jest and react-testing-library</li>
          <li>Maximize lighthouse score</li>
          <li>GH actions</li>
        </ul>
        <Button className="mt-4">My custom button from UI</Button>
      </div>
    </div>
  </div>
);

export default Web;
